name: Deploy to shinyapps.io
on:
  # run on any push
  push:

  # run on request (via button in actions menu)
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to shinyapps

    # allow skipping deployment for commits containing '[automated]' or '[no-deploy]' in the commit message
    if: "!contains(github.event.head_commit.message, '[automated]') && !contains(github.event.head_commit.message, '[no-deploy]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to shiny.io
        run: |
          Rscript -e "
              install.packages('rsconnect');
              rsconnect::setAccountInfo(name='forrt-replications', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}});
              if (!require(remotes)) install.packages('remotes');
              remotes::install_github('forrtproject/FReD');
              appDir <- system.file('fred_explorer', package = 'FReD');
              rsconnect::deployApp(appDir);
              appDir <- system.file('fred_annotator', package = 'FReD');
              rsconnect::deployApp(appDir);
          "
