# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: CMD check

on:
  push:
  pull_request:

env:
  _R_CHECK_FORCE_SUGGESTS_: "false"

jobs:
  ci:
    strategy:
      matrix:
        include:
          - {os: macOS-latest}
          - {os: ubuntu-latest}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Setup
        uses: eddelbuettel/github-actions/r-ci-setup@master

      #- name: Bootstrap
      #  run: ./run.sh bootstrap

      #- name: Dependencies
      #  run: ./run.sh install_deps

      - name: All Dependencies
        run: ./run.sh install_all

      - name: Create documentation
        run: |
          R -e "
            install.packages(c('rcmdcheck', 'roxygen2', 'devtools'));
            file.remove('NAMESPACE');
            descr <- readLines('DESCRIPTION');
            descr <- stringr::str_replace(descr, '^Date.*$', paste('Date:', Sys.Date()));
            writeLines(descr, 'DESCRIPTION');
            roxygen2::roxygenise();
            try(devtools::build_manual())
          "

      - name: commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -f man/\* NAMESPACE
          git commit -m 'Documentation' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

      - uses: r-lib/actions/check-r-package@v2
